apiVersion: v1
kind: Service
metadata:
  name: client
  namespace: dsa-genie
  labels:
    app: dsa-genie
    component: client
spec:
  type: ClusterIP
  selector:
    app: dsa-genie
    component: client
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
