apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: dsa-genie
  labels:
    app: dsa-genie
    component: server
spec:
  type: ClusterIP
  selector:
    app: dsa-genie
    component: server
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
